### ISSUE TITLE
ClassNotFoundException even when class is in correct folder

### ISSUE THREAD

**Issue by spaceemotion** [mountainblade/modular#2]
_Continuation of [this twitter conversation](https://twitter.com/badlogicgames/status/609730497711841280)_

**As described by @badlogic:**
![](http://libgdx.badlogicgames.com/uploads/Screen%20Shot%202015-06-13%20at%2016.33.41-b2shEq9dag.png)
Fails with a class not found exception. The class is definitely in the bin/ folder.

**Comment by spaceemotion** [comment]
How does the content of the bin folder look like? does it contain the full "com/example/Thing.class" hierarchy?

**Comment by badlogic** [comment]
Looks like this:

```
badlogic@Marios-MacBook-Pro:~/workspaces/zeno/zeno/zeno-editor/bin$ find .
.
./zeno
./zeno/plugins
./zeno/plugins/DefaultMenu.class
```

Using any other strategy doesn't help either.

**Comment by badlogic** [comment]
The instantiation of `DefaultModuleManager` creates a new `ClassRealm`, using the base class loader fetched via `BaseModuleManager.class.getClassLoader()`, and a `LOCAL_CLASSPATH` of `[file:/Users/badlogic/workspaces/zeno/zeno/zeno-editor-runtime/bin/]`, which is the bin folder of the app that i'm running. All of that looks OK.

Then the call to `loadModules` happens. In `BaseModuleManager.java:202`, `getClasses()` is called. That traverses the directory and fills a map of URIs to binary class names.

```
{file:/Users/badlogic/workspaces/zeno/zeno/zeno-editor/bin/zeno/plugins/=[DefaultMenu]}
```

That's passed to `ModuleLoader#filter()` which does the actual class loading via the `ClassRealm`. In line  127, the binary class name is passed to the `ClassRealm`. None of its loaders has any idea about the `bin/` directory, it's never passed to the realm anywhere.

I guess that's what makes things go boom?

**Comment by spaceemotion** [comment]
Okay, so this is actually a bug and has nothing to do with strategies.

I fixed this in https://github.com/mountainblade/modular/commit/62e2ecf0d02f845ba24fe3da4126fcb69bd2e271 by setting the root folder properly.
Let's hope this works! The unit test passes…

**Comment by badlogic** [comment]
Works! Thanks for the quick fix!

**Comment by spaceemotion** [comment]
No problem :)

I guess I will start finalizing version 1.0. In addition to the javadocs I might pull out some inner classes and simplify the custom injection as well as adding more examples to the readme. 

To be honest, I have never thought that this project would be used so quickly by others, guess that's the power of OSS!

Edit: You can also just call the `loadModules(new File(...))` method directly, no need to convert it to a URI first.

**Comment by badlogic** [comment]
It's brilliant, super lightweight and quite untuitive. I'll probably run
into a few more issues and hope i can help fix some :)

Thanks for your effort!
