### ISSUE TITLE
add jar to maven repo

### ISSUE THREAD

**Issue by htynkn** [mountainblade/modular#3]
Hi spaceemotion,

I'm using modular and I notice that looks like the repo[serkprojects.com] is not available.

Could you put a release version of modular to maven central repo?

Thanks

**Comment by azakhary** [comment]
It seems to be still not working, I am going to build jar and use it directly from libs folder.

**Comment by spaceemotion** [comment]
Hey, @htynkn @azakhary - thank you for using modular!
Sadly our build server is dying on us on occasion. I am currently working on getting modular moved to maven central. Should be available at the end of this week, updates will be posted here :)

**Comment by azakhary** [comment]
thanks a lot. modular is awesome!

**Comment by spaceemotion** [comment]
Sorry for the wait, I was out of town for a few days. The ticket for the sonartype nexus / maven central has been created (https://issues.sonatype.org/browse/OSSRH-17841).

Let's hope for the best :)

**Comment by spaceemotion** [comment]
Okay, looks like everything went well. If anything else comes up, just create a new issue :)
Cheers!

**Comment by azakhary** [comment]
Thanks!
