### ISSUE TITLE
Loading images/resources from external jar

### ISSUE THREAD

**Issue by azakhary** [mountainblade/modular#4]
Hi,

I've been using modular for quite some time for our plugin system for Overlap2D.
Lately we needed to make a plugin that comes with it's own icons/images. I am not sure how do I load them, here is the stackoverflow question : [http://stackoverflow.com/questions/36674763/reading-images-from-external-jar/36675382](url)

What's the best way to do this while using modular?

Thanks.

**Comment by spaceemotion** [comment]
Hey @azakhary, thanks for using this package! First of all, modular encapsulates the modules it loads to prevent any possible "damage" so it can be easily unloaded again.

Which means, that if you want to load a certain resource from a module, you have to do so from within  that module or using its class(loader), like I did in this example (https://github.com/mountainblade/modular/commit/87fdd42cb72354826fecec212d91ee0522fa34fa):

``` java
@Initialize
public void initialize() {
    //  Load some images
    try (InputStream stream = getClass().getResourceAsStream("/openProject.png")) {
        // Do something with it here.
    }
}
```

Hope this helps!

**Comment by spaceemotion** [comment]
@azakhary I will close this issue due to inactivity, if you still have trouble loading resources, just reopen it again!

**Comment by azakhary** [comment]
Oh, sorry I though I did reply, apparently I did not :) The solution you suggested worked just fine, thanks!

**Comment by spaceemotion** [comment]
Alright, thanks!
